from fastapi import FastAPI, UploadFile, File, Form, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer
from pydantic import BaseModel, EmailStr
from typing import Optional, Dict
import uvicorn
import os
import tempfile
import pathlib
import uuid
import bcrypt
import jwt
import random
import shutil
import time
import glob
from datetime import datetime, timezone, timedelta
from azure.cosmos import CosmosClient
from dotenv import load_dotenv
from concurrent.futures import ThreadPoolExecutor, as_completed
import concurrent.futures
from openai import OpenAI, AzureOpenAI

load_dotenv()

COSMOS_ENDPOINT = os.getenv("COSMOS_ENDPOINT")
COSMOS_KEY = os.getenv("COSMOS_KEY")
DATABASE_NAME = os.getenv("COSMOS_DATABASE")
USERS_CONTAINER = os.getenv("COSMOS_USERS_CONTAINER", "users")

SECRET_KEY = os.getenv("JWT_SECRET", "threadnotes-super-secret-key")
ALGORITHM = "HS256"

MAX_WORKERS = int(os.getenv("MAX_WORKERS", 6))

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="login")
client = CosmosClient(COSMOS_ENDPOINT, COSMOS_KEY)
database = client.get_database_client(DATABASE_NAME)
users_cont = database.get_container_client(USERS_CONTAINER)

progress_tracker: Dict[str, Dict[str, int]] = {}
otp_storage: Dict[str, str] = {}
signup_otp_storage: Dict[str, str] = {}

class UserSignup(BaseModel):
    name: str
    email: EmailStr
    password: str

class UserLogin(BaseModel):
    email: EmailStr
    password: str

class OTPRequest(BaseModel):
    email: EmailStr

class OTPVerifyRequest(BaseModel):
    email: EmailStr
    otp: str

class ForgotPasswordRequest(BaseModel):
    email: EmailStr

class ResetPasswordRequest(BaseModel):
    email: EmailStr
    otp: str
    new_password: str

def send_otp_email(target_email: str, otp: str, subject_prefix: str):
    subject = f"ThreadNotes — {subject_prefix} OTP"
    html_content = f"""\
<div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:480px;margin:0 auto;padding:24px;color:#0f172a">
  <h2 style="margin:0 0 8px">ThreadNotes</h2>
  <p style="margin:0 0 16px;color:#475569">Your OTP for <strong>{subject_prefix}</strong> is:</p>
  <div style="font-size:32px;font-weight:700;letter-spacing:8px;padding:16px 0;text-align:center;background:#f1f5f9;border-radius:12px;color:#4f46e5">{otp}</div>
  <p style="margin:16px 0 0;font-size:13px;color:#94a3b8">This code expires shortly. Please do not share it with anyone.</p>
</div>"""

    try:
        from email_service import _send_sync
        _send_sync(target_email, subject, html_content)
    except Exception as e:
        print(f"[email] OTP dispatch FAILED for {target_email}: {type(e).__name__}: {e}")
        raise HTTPException(status_code=500, detail="Failed to send verification email.")

# --- THE GPT-4o EDITOR LOGIC WITH CHUNK TRACKING ---
def refine_transcript_with_gpt(raw_text: str) -> str:
    """Fixes speaker tags across chunks with explicit context."""
    if not raw_text or not raw_text.strip():
        return raw_text

    api_key = (os.getenv("AZURE_OPENAI_KEY") or os.getenv("OPENAI_API_KEY") or "").strip()
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT", "").strip()
    api_version = os.getenv("AZURE_OPENAI_API_VERSION", "2025-04-01-preview").strip()
    deployment = os.getenv("AZURE_DIARIZE_DEPLOYMENT", "gpt-4o").strip()

    try:
        if azure_endpoint:
            llm_client = AzureOpenAI(api_key=api_key, api_version=api_version, azure_endpoint=azure_endpoint)
            model_name = deployment
        else:
            llm_client = OpenAI(api_key=api_key)
            model_name = "gpt-4o"

        system_prompt = """You are an expert transcript editor for professional meetings. 
        The transcript below was generated by an AI that processed the audio in smaller chunks. 
        Because of this, the speaker tags (e.g., [Speaker 1], [Speaker 2]) RESET at every '--- CHUNK X ---' marker.
        For example, 'Speaker 1' in CHUNK 1 might be a completely different person than 'Speaker 1' in CHUNK 2.
        
        Your task:
        1. Read the flow of the conversation carefully.
        2. Identify the logical distinct speakers (e.g., Interviewer, Candidate, Boy, Girl, Client, etc.).
        3. Replace all the reset tags with consistent GLOBAL speaker names across the entire transcript (e.g., [Person A], [Person B], [Person C]).
        4. Remove the '--- CHUNK X ---' markers from your final output.
        5. DO NOT summarize or alter the actual spoken text. Output ONLY the fully corrected transcript."""

        response = llm_client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Here is the raw transcript:\n\n{raw_text}"}
            ],
            temperature=0.1
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"GPT Refinement failed: {e}")
        return raw_text


from transcriber import Transcriber
from thick_client import router as thick_client_router, get_current_user

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(thick_client_router)


class MeetingEmailRequest(BaseModel):
    to: EmailStr
    title: str
    summary_html: str


@app.post("/api/send-notes")
async def send_notes(
    req: MeetingEmailRequest, user: dict = Depends(get_current_user)
):
    owner = str(user.get("sub", "")).strip().lower()
    if not owner or req.to.strip().lower() != owner:
        raise HTTPException(
            status_code=403, detail="You can only email your own account."
        )

    if any(c in req.title for c in ("\r", "\n")) or len(req.title) > 200:
        raise HTTPException(status_code=400, detail="Invalid meeting title.")

    try:
        from email_service import send_meeting_email
    except Exception as e:
        return {"status": "error", "message": f"Email service unavailable: {e}"}

    result = await send_meeting_email(
        to_email=req.to,
        subject=f"ThreadNotes — {req.title}",
        html_content=req.summary_html,
    )
    if not result.get("success"):
        return {"status": "error", "message": result.get("error")}
    return {"status": "success", "id": result.get("id")}


@app.post("/send-signup-otp")
def send_signup_otp(req: OTPRequest):
    query = "SELECT * FROM c WHERE c.email = @email"
    params = [{"name": "@email", "value": req.email}]
    exists = list(users_cont.query_items(query, parameters=params, enable_cross_partition_query=True))
    if exists:
        raise HTTPException(status_code=400, detail="Email already registered. Please log in.")

    otp = str(random.randint(100000, 999999))
    signup_otp_storage[req.email] = otp
    send_otp_email(req.email, otp, "Signup Verification")
    return {"status": "success", "message": "Verification OTP sent successfully."}

@app.post("/verify-signup-otp")
def verify_signup_otp(req: OTPVerifyRequest):
    if signup_otp_storage.get(req.email) != req.otp:
        raise HTTPException(status_code=400, detail="Invalid or expired verification OTP")
    return {"status": "success", "message": "Email verified successfully."}

@app.post("/signup")
def signup(user: UserSignup):
    query = "SELECT * FROM c WHERE c.email = @email"
    exists = list(users_cont.query_items(query, parameters=[{"name": "@email", "value": user.email}], enable_cross_partition_query=True))
    if exists: raise HTTPException(status_code=400, detail="Email already registered")

    hashed_pw = bcrypt.hashpw(user.password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    user_doc = {
        "id": str(uuid.uuid4()), "tenantId": str(uuid.uuid4()), "name": user.name,
        "email": user.email, "password": hashed_pw, "createdAt": datetime.now(timezone.utc).isoformat()
    }
    users_cont.create_item(user_doc)
    signup_otp_storage.pop(user.email, None)
    return {"status": "success", "message": "Account created"}

@app.post("/login")
def login(user: UserLogin):
    query = "SELECT * FROM c WHERE c.email = @email"
    user_list = list(users_cont.query_items(query, parameters=[{"name": "@email", "value": user.email}], enable_cross_partition_query=True))
    if not user_list or not bcrypt.checkpw(user.password.encode('utf-8'), user_list[0]['password'].encode('utf-8')):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    token_data = {"sub": user_list[0]['email'], "tenantId": user_list[0]['tenantId'], "exp": datetime.utcnow() + timedelta(hours=24)}
    return {"access_token": jwt.encode(token_data, SECRET_KEY, algorithm=ALGORITHM), "token_type": "bearer", "name": user_list[0]['name']}

@app.post("/forgot-password")
def forgot_password(req: ForgotPasswordRequest):
    email = req.email.strip().lower()
    user_list = list(users_cont.query_items(
        "SELECT * FROM c WHERE LOWER(c.email) = @email",
        parameters=[{"name": "@email", "value": email}],
        enable_cross_partition_query=True,
    ))
    if not user_list:
        return {"status": "success", "message": "If an account exists, a reset OTP has been sent."}

    otp = str(random.randint(100000, 999999))
    otp_storage[email] = otp

    try:
        send_otp_email(user_list[0]["email"], otp, "Password Reset")
    except Exception as e:
        raise HTTPException(status_code=500, detail="Failed to send reset OTP.")

    return {"status": "success", "message": "If an account exists, a reset OTP has been sent."}

@app.post("/reset-password")
def reset_password(req: ResetPasswordRequest):
    email = req.email.strip().lower()
    if otp_storage.get(email) != req.otp: raise HTTPException(status_code=400, detail="Invalid or expired OTP")

    user_list = list(users_cont.query_items("SELECT * FROM c WHERE LOWER(c.email) = @email", parameters=[{"name": "@email", "value": email}], enable_cross_partition_query=True))
    if not user_list: raise HTTPException(status_code=404, detail="User not found")

    user_doc = user_list[0]
    user_doc['password'] = bcrypt.hashpw(req.new_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    users_cont.upsert_item(user_doc)
    otp_storage.pop(email, None)
    return {"status": "success", "message": "Password updated successfully!"}

@app.delete("/delete-account")
def delete_account(user: dict = Depends(get_current_user)):
    email = str(user.get("sub", "")).strip()
    if not email:
        raise HTTPException(status_code=401, detail="Invalid session")

    matches = list(users_cont.query_items(
        "SELECT * FROM c WHERE c.email = @email",
        parameters=[{"name": "@email", "value": email}],
        enable_cross_partition_query=True,
    ))
    if not matches:
        raise HTTPException(status_code=404, detail="User not found")

    pk_field = users_cont.read()["partitionKey"]["paths"][0].lstrip("/")
    for doc in matches:
        users_cont.delete_item(item=doc["id"], partition_key=doc.get(pk_field))

    otp_storage.pop(email, None)
    signup_otp_storage.pop(email, None)
    return {"status": "success", "message": "Account deleted"}

@app.get("/progress/{filename}")
async def get_progress(filename: str):
    return progress_tracker.get(filename, {"current": 0, "total": 1})

@app.post("/transcribe")
def process_meeting(file: UploadFile = File(...), meeting_type: str = Form("General")):
    tmp_path = None
    filename = file.filename
    progress_tracker[filename] = {"current": 0, "total": 1}

    try:
        file_ext = pathlib.Path(filename.lower()).suffix
        audio_exts = {'.mp3', '.wav', '.webm', '.m4a', '.mpeg', '.mp4'}
        doc_exts = {'.docx', '.txt'}

        if file_ext in audio_exts:
            with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as tmp:
                shutil.copyfileobj(file.file, tmp)
                tmp_path = tmp.name

            chunk_dir = tempfile.mkdtemp()
            chunk_files = []
            
            # --- HIGH QUALITY VAD CHUNKING (Prevents Audio Flattening) ---
            try:
                from pydub import AudioSegment
                from pydub.silence import split_on_silence
                
                audio = AudioSegment.from_file(tmp_path)
                
                raw_chunks = split_on_silence(
                    audio,
                    min_silence_len=1000,
                    silence_thresh=audio.dBFS - 14,
                    keep_silence=500
                )
                if not raw_chunks:
                    raw_chunks = [audio]

                target_length = 45 * 1000 
                grouped_chunks = []
                current_chunk = AudioSegment.empty()
                
                for c in raw_chunks:
                    current_chunk += c
                    if len(current_chunk) >= target_length:
                        grouped_chunks.append(current_chunk)
                        current_chunk = AudioSegment.empty()
                if len(current_chunk) > 0:
                    grouped_chunks.append(current_chunk)

                for i, gc in enumerate(grouped_chunks):
                    c_path = os.path.join(chunk_dir, f"chunk_{i:04d}.wav")
                    gc.export(c_path, format="wav") # Preserves high quality for Diarization
                    chunk_files.append(c_path)
                    
            except Exception as e:
                print(f"VAD Chunking failed: {e}")
                raise HTTPException(status_code=500, detail="Audio chunking failed.")

            ts = Transcriber()
            transcript_parts = {}
            active_futures = {}
            
            progress_tracker[filename]["total"] = max(1, len(chunk_files))

            def process_single_chunk(idx, chunk_path):
                max_retries = 2
                backoff_time = 2
                for attempt in range(max_retries):
                    try:
                        text = ts.diarize_chunk_file(chunk_path)
                        if os.path.exists(chunk_path):
                            os.remove(chunk_path)
                        return idx, text
                    except Exception:
                        if attempt < max_retries - 1:
                            time.sleep(backoff_time)
                            backoff_time *= 2
                        else:
                            if os.path.exists(chunk_path):
                                os.remove(chunk_path)
                            return idx, ""

            with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
                for idx, chunk_path in enumerate(chunk_files):
                    future = executor.submit(process_single_chunk, idx, chunk_path)
                    active_futures[future] = idx

                for future in concurrent.futures.as_completed(active_futures.keys(), timeout=300):
                    try:
                        idx, text = future.result(timeout=60)
                        if text:
                            transcript_parts[idx] = text
                    except concurrent.futures.TimeoutError:
                        print("Timeout error in a chunk")
                    except Exception as e:
                        print(f"Chunk processing error: {e}")
                    
                    progress_tracker[filename]["current"] += 1

            # --- ADDING CHUNK MARKERS FOR GPT CONTEXT ---
            raw_final_text = ""
            for i in sorted(transcript_parts.keys()):
                if transcript_parts[i].strip():
                    raw_final_text += f"\n\n--- CHUNK {i+1} ---\n{transcript_parts[i].strip()}"
            
            # --- APPLY GPT-4o CORRECTION ON THE RAW TEXT ---
            final_text = refine_transcript_with_gpt(raw_final_text)

            progress_tracker.pop(filename, None)

            if tmp_path and os.path.exists(tmp_path):
                os.remove(tmp_path)
            if os.path.exists(chunk_dir):
                shutil.rmtree(chunk_dir, ignore_errors=True)

            return {"status": "success", "meeting_type": meeting_type, "transcript": final_text}

        elif file_ext in doc_exts:
            content = file.file.read()
            if file_ext == '.docx':
                import io
                from docx import Document
                doc = Document(io.BytesIO(content))
                text = " ".join([p.text for p in doc.paragraphs if p.text.strip()])
            else:
                text = content.decode('utf-8', errors='ignore')
            return {"status": "success", "meeting_type": meeting_type, "transcript": text}
        return {"status": "error", "message": "Unsupported format"}

    except Exception as e:
        progress_tracker.pop(filename, None)
        if tmp_path and os.path.exists(tmp_path):
            os.remove(tmp_path)
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)